name: three_experiment
description: webgl rendrer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  three_dart: ^0.0.11
  flutter_gl: ^0.0.18
  three_dart_jsm: ^0.0.6
  sensors_plus: ^1.3.4
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/nes/
    - assets/